language: php

php:
  - 8.0
  - 8.1
  - 8.2

env:
  - LARAVEL_VERSION=^6.0
  - LARAVEL_VERSION=^7.0
  - LARAVEL_VERSION=^8.0
  - LARAVEL_VERSION=^9.0
  - LARAVEL_VERSION=^10.0

before_script:
  - travis_retry composer self-update
  - composer require laravel/framework:${LARAVEL_VERSION}
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - php vendor/bin/phpunit --coverage-text
